# Q1. What's the version of NumPy that you installed?

In [ ]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.20.1'

In [3]:
#data=wget 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
# !wget $data

In [4]:
#Loading the Dataset
csv_data='data.csv'
df=pd.read_csv(csv_data)
df.head(2)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650

# Q2. How many records are in the dataset?

In [5]:
len(df)

11914

# Q3. Who are the most frequent car manufacturers (top-3) in the dataset?

In [6]:
df.Make.value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Q4. What's the number of unique Audi car models in the dataset?

In [7]:
fff=df.groupby('Make').Model.unique()
dd=fff.loc['Audi']
dd

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [8]:
count=0
for i in dd:
    count +=1
print(count)

34

# Q5. How many columns in the dataset have missing values?

In [9]:
a=df.isnull().sum()
list(a)

[0, 0, 0, 3, 69, 30, 0, 0, 6, 3742, 0, 0, 0, 0, 0, 0]

In [10]:
columns=0
for i in a:
    if i>0:
        columns +=1
print(columns)

5

# Q6.

1. Find the median value of "Engine Cylinders" column in the dataset.

In [11]:
df['Engine Cylinders'].median()

6.0

2. Next, calculate the most frequent value of the same "Engine Cylinders".

In [12]:
df['Engine Cylinders'].value_counts().head(1)

4.0    4752
Name: Engine Cylinders, dtype: int64

OR

In [13]:
df['Engine Cylinders'].mode()

0    4.0
dtype: float64

3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

In [14]:
df['Engine Cylinders']=df['Engine Cylinders'].fillna(4.0)
df['Engine Cylinders'].isnull().sum()

0

4. Now, calculate the median value of "Engine Cylinders" once again.

In [15]:
df['Engine Cylinders'].median()

6.0

# Q7.

1. Select all the "Lotus" cars from the dataset.

In [16]:
df[df=="Lotus"].count().head(5)

Make                29
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
dtype: int64

In [18]:
df[df['Make']=='Lotus']

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
3912,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3913,Lotus,Elise,2009,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3914,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3915,Lotus,Elise,2010,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3917,Lotus,Elise,2011,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3918,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3919,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4216,Lotus,Esprit,2002,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4217,Lotus,Esprit,2003,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4218,Lotus,Esprit,2004,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4257,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4258,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4260,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4261,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4262,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4263,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4264,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4265,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4266,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4267,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4268,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4292,Lotus,Exige,2009,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4293,Lotus,Exige,2009,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4294,Lotus,Exige,2010,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2011,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4297,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950

2. Select only columns "Engine HP", "Engine Cylinders".

In [19]:
df[['Engine HP', 'Engine Cylinders']].head(3)

   Engine HP  Engine Cylinders
0      335.0               6.0
1      300.0               6.0
2      300.0               6.0

4. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

In [20]:
dups=df.drop_duplicates()
dups.head(9)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900

In [21]:
a=df.dtypes
index=[]
for i,b in enumerate(a):
    if b!='object':
        index +=[i]
ab=list(df.columns.values)
col_names=[]
for ia, ab in enumerate(ab):
    for i in index:
        if ia==i:
            col_names +=[ab]
col_names

['Year',
 'Engine HP',
 'Engine Cylinders',
 'Number of Doors',
 'highway MPG',
 'city mpg',
 'Popularity',
 'MSRP']

In [22]:
cols=df[col_names].head(15)
cols

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
0,2011,335.0,6.0,2.0,26,19,3916,46135
1,2011,300.0,6.0,2.0,28,19,3916,40650
2,2011,300.0,6.0,2.0,28,20,3916,36350
3,2011,230.0,6.0,2.0,28,18,3916,29450
4,2011,230.0,6.0,2.0,28,18,3916,34500
5,2012,230.0,6.0,2.0,28,18,3916,31200
6,2012,300.0,6.0,2.0,26,17,3916,44100
7,2012,300.0,6.0,2.0,28,20,3916,39300
8,2012,230.0,6.0,2.0,28,18,3916,36900
9,2013,230.0,6.0,2.0,27,18,3916,37200
10,2013,300.0,6.0,2.0,28,20,3916,39600
11,2013,230.0,6.0,2.0,28,19,3916,31500
12,2013,300.0,6.0,2.0,28,19,3916,44400
13,2013,230.0,6.0,2.0,28,19,3916,37200
14,2013,230.0,6.0,2.0,28,19,3916,31500

5. Get the underlying NumPy array. Let's call it X.

In [23]:
#X=np.array(two_cols)
X =np.array(cols)
X

array([[2.0110e+03, 3.3500e+02, 6.0000e+00, 2.0000e+00, 2.6000e+01,
        1.9000e+01, 3.9160e+03, 4.6135e+04],
       [2.0110e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.9000e+01, 3.9160e+03, 4.0650e+04],
       [2.0110e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        2.0000e+01, 3.9160e+03, 3.6350e+04],
       [2.0110e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.8000e+01, 3.9160e+03, 2.9450e+04],
       [2.0110e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.8000e+01, 3.9160e+03, 3.4500e+04],
       [2.0120e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.8000e+01, 3.9160e+03, 3.1200e+04],
       [2.0120e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.6000e+01,
        1.7000e+01, 3.9160e+03, 4.4100e+04],
       [2.0120e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        2.0000e+01, 3.9160e+03, 3.9300e+04],
       [2.0120e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.8000e+01, 3.9160e+03, 3.6900e+04],
       [2.0130e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.7000e+01,
        1.8000e+01, 3.9160e+03, 3.7200e+04],
       [2.0130e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        2.0000e+01, 3.9160e+03, 3.9600e+04],
       [2.0130e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.9000e+01, 3.9160e+03, 3.1500e+04],
       [2.0130e+03, 3.0000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.9000e+01, 3.9160e+03, 4.4400e+04],
       [2.0130e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.9000e+01, 3.9160e+03, 3.7200e+04],
       [2.0130e+03, 2.3000e+02, 6.0000e+00, 2.0000e+00, 2.8000e+01,
        1.9000e+01, 3.9160e+03, 3.1500e+04]])

6. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.

In [24]:
X_t=X.transpose()
XTX=X.dot(X_t)
XTX

array([[2.14793070e+09, 1.89486856e+09, 1.69648808e+09, 1.37813309e+09,
        1.61111484e+09, 1.45887135e+09, 2.05403623e+09, 1.83258834e+09,
        1.72184085e+09, 1.73568333e+09, 1.84643085e+09, 1.47271388e+09,
        2.06787883e+09, 1.73568338e+09, 1.47271388e+09],
       [1.89486856e+09, 1.67189286e+09, 1.49709788e+09, 1.21659184e+09,
        1.42187434e+09, 1.28773135e+09, 1.81213728e+09, 1.61701739e+09,
        1.51943635e+09, 1.53163334e+09, 1.62921440e+09, 1.29992838e+09,
        1.82433438e+09, 1.53163338e+09, 1.29992838e+09],
       [1.69648808e+09, 1.49709788e+09, 1.34079290e+09, 1.08995686e+09,
        1.27352436e+09, 1.15357137e+09, 1.62250730e+09, 1.44802741e+09,
        1.36076637e+09, 1.37167336e+09, 1.45893442e+09, 1.16447840e+09,
        1.63341440e+09, 1.37167340e+09, 1.16447840e+09],
       [1.37813309e+09, 1.21659184e+09, 1.08995686e+09, 8.86735725e+08,
        1.03545822e+09, 9.38275236e+08, 1.31819626e+09, 1.17683637e+09,
        1.10614024e+09, 1.11497722e+09, 1.18567338e+09, 9.47112265e+08,
        1.32703336e+09, 1.11497726e+09, 9.47112265e+08],
       [1.61111484e+09, 1.42187434e+09, 1.27352436e+09, 1.03545822e+09,
        1.20968322e+09, 1.09583524e+09, 1.54090126e+09, 1.37530137e+09,
        1.29248524e+09, 1.30283722e+09, 1.38565338e+09, 1.10618726e+09,
        1.55125336e+09, 1.30283726e+09, 1.10618726e+09],
       [1.45887135e+09, 1.28773135e+09, 1.15357137e+09, 9.38275236e+08,
        1.09583524e+09, 9.92877248e+08, 1.39537327e+09, 1.24561338e+09,
        1.17071725e+09, 1.18007923e+09, 1.25497540e+09, 1.00223928e+09,
        1.40473538e+09, 1.18007928e+09, 1.00223928e+09],
       [2.05403623e+09, 1.81213728e+09, 1.62250730e+09, 1.31819626e+09,
        1.54090126e+09, 1.39537327e+09, 1.96428420e+09, 1.75260431e+09,
        1.64674327e+09, 1.65997526e+09, 1.76583632e+09, 1.40860530e+09,
        1.97751630e+09, 1.65997530e+09, 1.40860530e+09],
       [1.83258834e+09, 1.61701739e+09, 1.44802741e+09, 1.17683637e+09,
        1.37530137e+09, 1.24561338e+09, 1.75260431e+09, 1.56396442e+09,
        1.46962338e+09, 1.48141537e+09, 1.57575644e+09, 1.25740542e+09,
        1.76439642e+09, 1.48141542e+09, 1.25740542e+09],
       [1.72184085e+09, 1.51943635e+09, 1.36076637e+09, 1.10614024e+09,
        1.29248524e+09, 1.17071725e+09, 1.64674327e+09, 1.46962338e+09,
        1.38104725e+09, 1.39211923e+09, 1.48069540e+09, 1.18178928e+09,
        1.65781538e+09, 1.39211928e+09, 1.18178928e+09],
       [1.73568333e+09, 1.53163334e+09, 1.37167336e+09, 1.11497722e+09,
        1.30283722e+09, 1.18007923e+09, 1.65997526e+09, 1.48141537e+09,
        1.39211923e+09, 1.40328122e+09, 1.49257738e+09, 1.19124126e+09,
        1.67113736e+09, 1.40328126e+09, 1.19124126e+09],
       [1.84643085e+09, 1.62921440e+09, 1.45893442e+09, 1.18567338e+09,
        1.38565338e+09, 1.25497540e+09, 1.76583632e+09, 1.57575644e+09,
        1.48069540e+09, 1.49257738e+09, 1.58763845e+09, 1.26685743e+09,
        1.77771843e+09, 1.49257743e+09, 1.26685743e+09],
       [1.47271388e+09, 1.29992838e+09, 1.16447840e+09, 9.47112265e+08,
        1.10618726e+09, 1.00223928e+09, 1.40860530e+09, 1.25740542e+09,
        1.18178928e+09, 1.19124126e+09, 1.26685743e+09, 1.01169131e+09,
        1.41805741e+09, 1.19124131e+09, 1.01169131e+09],
       [2.06787883e+09, 1.82433438e+09, 1.63341440e+09, 1.32703336e+09,
        1.55125336e+09, 1.40473538e+09, 1.97751630e+09, 1.76439642e+09,
        1.65781538e+09, 1.67113736e+09, 1.77771843e+09, 1.41805741e+09,
        1.99083841e+09, 1.67113741e+09, 1.41805741e+09],
       [1.73568338e+09, 1.53163338e+09, 1.37167340e+09, 1.11497726e+09,
        1.30283726e+09, 1.18007928e+09, 1.65997530e+09, 1.48141542e+09,
        1.39211928e+09, 1.40328126e+09, 1.49257743e+09, 1.19124131e+09,
        1.67113741e+09, 1.40328131e+09, 1.19124131e+09],
       [1.47271388e+09, 1.29992838e+09, 1.16447840e+09, 9.47112265e+08,
        1.10618726e+09, 1.00223928e+09, 1.40860530e+09, 1.25740542e+09,
        1.18178928e+09, 1.19124126e+09, 1.26685743e+09, 1.01169131e+09,
        1.41805741e+09, 1.19124131e+09, 1.01169131e+09]])

In [25]:
inv_XTX=np.linalg.pinv(XTX).round(2)

In [26]:
inv_XTX

array([[ 0.21, -0.08,  0.07, -0.03,  0.02, -0.09, -0.09,  0.02, -0.03,
         0.1 , -0.05,  0.03, -0.19,  0.09,  0.03],
       [-0.08,  0.06, -0.01,  0.02,  0.03,  0.03,  0.  , -0.  ,  0.04,
        -0.06, -0.  , -0.04,  0.07, -0.03, -0.04],
       [ 0.07, -0.01,  0.03, -0.01,  0.02, -0.04, -0.05,  0.01,  0.  ,
         0.02, -0.02, -0.  , -0.06,  0.04, -0.  ],
       [-0.03,  0.02, -0.01,  0.02,  0.01,  0.02,  0.03, -0.01,  0.01,
        -0.02, -0.  , -0.01,  0.03, -0.03, -0.01],
       [ 0.02,  0.03,  0.02,  0.01,  0.05, -0.02, -0.04,  0.01,  0.03,
        -0.01, -0.03, -0.03, -0.02,  0.01, -0.03],
       [-0.09,  0.03, -0.04,  0.02, -0.02,  0.05,  0.07, -0.02,  0.01,
        -0.04,  0.02, -0.01,  0.08, -0.05, -0.01],
       [-0.09,  0.  , -0.05,  0.03, -0.04,  0.07,  0.11, -0.03, -0.01,
        -0.02,  0.02,  0.01,  0.07, -0.07,  0.01],
       [ 0.02, -0.  ,  0.01, -0.01,  0.01, -0.02, -0.03,  0.01,  0.  ,
         0.01, -0.  ,  0.  , -0.02,  0.02,  0.  ],
       [-0.03,  0.04,  0.  ,  0.01,  0.03,  0.01, -0.01,  0.  ,  0.02,
        -0.03, -0.01, -0.02,  0.03, -0.01, -0.02],
       [ 0.1 , -0.06,  0.02, -0.02, -0.01, -0.04, -0.02,  0.01, -0.03,
         0.06, -0.01,  0.03, -0.09,  0.04,  0.03],
       [-0.05, -0.  , -0.02, -0.  , -0.03,  0.02,  0.02, -0.  , -0.01,
        -0.01,  0.03,  0.01,  0.05, -0.02,  0.01],
       [ 0.03, -0.04, -0.  , -0.01, -0.03, -0.01,  0.01,  0.  , -0.02,
         0.03,  0.01,  0.02, -0.02,  0.01,  0.02],
       [-0.19,  0.07, -0.06,  0.03, -0.02,  0.08,  0.07, -0.02,  0.03,
        -0.09,  0.05, -0.02,  0.17, -0.08, -0.02],
       [ 0.09, -0.03,  0.04, -0.03,  0.01, -0.05, -0.07,  0.02, -0.01,
         0.04, -0.02,  0.01, -0.08,  0.06,  0.01],
       [ 0.03, -0.04, -0.  , -0.01, -0.03, -0.01,  0.01,  0.  , -0.02,
         0.03,  0.01,  0.02, -0.02,  0.01,  0.02]])

7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

In [27]:
y=np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [29]:
XTX_X=X_t.dot(XTX)
XTX_X

array([[5.25690786e+13, 4.63887185e+13, 4.15438053e+13, 3.37688477e+13,
        3.94588046e+13, 3.57406757e+13, 5.02759747e+13, 4.48677022e+13,
        4.21630033e+13, 4.25010804e+13, 4.52057801e+13, 3.60787542e+13,
        5.06140554e+13, 4.25010818e+13, 3.60787542e+13],
       [7.03219760e+12, 6.20530342e+12, 5.55708398e+12, 4.51684235e+12,
        5.27812341e+12, 4.78066062e+12, 6.72539415e+12, 6.00180072e+12,
        5.63992835e+12, 5.68516085e+12, 6.04703333e+12, 4.82589331e+12,
        6.77062714e+12, 5.68516104e+12, 4.82589331e+12],
       [1.56761857e+11, 1.38331921e+11, 1.23884310e+11, 1.00699258e+11,
        1.17666803e+11, 1.06579281e+11, 1.49923783e+11, 1.33796225e+11,
        1.25730768e+11, 1.26738920e+11, 1.34804379e+11, 1.07587437e+11,
        1.50931946e+11, 1.26738924e+11, 1.07587437e+11],
       [5.22539523e+10, 4.61106403e+10, 4.12947698e+10, 3.35664192e+10,
        3.92222677e+10, 3.55264271e+10, 4.99745944e+10, 4.45987417e+10,
        4.19102561e+10, 4.22463066e+10, 4.49347931e+10, 3.58624790e+10,
        5.03106485e+10, 4.22463080e+10, 3.58624790e+10],
       [7.21415715e+11, 6.36603319e+11, 5.70117114e+11, 4.63422233e+11,
        5.41504879e+11, 4.90481411e+11, 6.89947705e+11, 6.15730583e+11,
        5.78614298e+11, 5.83253694e+11, 6.20369991e+11, 4.95120826e+11,
        6.94587151e+11, 5.83253713e+11, 4.95120826e+11],
       [4.89774338e+11, 4.32192871e+11, 3.87053561e+11, 3.14615470e+11,
        3.67627921e+11, 3.32986687e+11, 4.68409837e+11, 4.18021796e+11,
        3.92822522e+11, 3.95972334e+11, 4.21171616e+11, 3.36136512e+11,
        4.71559683e+11, 3.95972347e+11, 3.36136512e+11],
       [1.02313239e+14, 9.02846337e+13, 8.08551594e+13, 6.57230488e+13,
        7.67972002e+13, 6.95607442e+13, 9.78502558e+13, 8.73243363e+13,
        8.20602814e+13, 8.27182683e+13, 8.79823248e+13, 7.02187339e+13,
        9.85082498e+13, 8.27182711e+13, 7.02187339e+13],
       [9.92462743e+14, 8.75759813e+14, 7.84273945e+14, 6.37460450e+14,
        7.44903168e+14, 6.74694201e+14, 9.49162348e+14, 8.47038639e+14,
        7.95966180e+14, 8.02350027e+14, 8.53422502e+14, 6.81078074e+14,
        9.55546263e+14, 8.02350053e+14, 6.81078074e+14]])

In [32]:
w=y.dot(XTX_X)

9. What's the value of the first element of w?

In [35]:
w[0]

1.4575561506877486e+18